INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('10 Napa Ct.', 'Lebanon', '97355', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1000 Bidweld Street', 'Haney', 'V2W 1W2', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1002 N. Spoonwood Court', 'Hervey Bay', '4655', 'Queensland');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1003 Matterhorn Ct', 'Lebanon', '97355', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Matterhorn Ct.', 'Cambridge', 'CB4 4BZ', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Matterhorn Ct.', 'Mill Valley', '94941', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Tanager Court', 'Corvallis', '97330', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Tanager Court', 'Milsons Point', '2061', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1006 Deercreek Ln', 'Bellflower', '90706', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1006 Deercreek Ln', 'Torrance', '90505', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('101 Adobe Dr', 'Coffs Harbour', '2450', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('101 Adobe Dr', 'Puyallup', '98371', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('101, avenue de la Gare', 'Peterborough', 'PB12', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1010 Maple', 'Baltimore', '21201', 'Maryland');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1011 Yolanda Circle', 'Berkeley', '94704', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1011 Yolanda Circle', 'N. Vancouver', 'V7L 4J4', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1013 Holiday Hills Dr.', 'Bremerton', '98312', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1013 Holiday Hills Dr.', 'Gateshead', 'GA10', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1015 Lynwood Drive', 'Metchosin', 'V9', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Carletto Drive', 'Berkeley', '94704', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Mt. Davidson Court', 'Burien', '98168', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Mt. Davidson Court', 'London', 'SW8 4BG', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('102 Vista Place', 'Santa Monica', '90401', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1020 Book Road', 'Bremerton', '98312', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1020 Carletto Drive', 'Matraville', '2036', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1020 Carletto Drive', 'Santa Cruz', '95062', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1023 Hawkins Street', 'Lebanon', '97355', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1024 Walnut Blvd.', 'Colma', '94014', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1025 Holly Oak Drive', 'Leeds', 'LE18', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1025 R St.', 'Kirkland', '98033', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1025 Yosemite Dr.', 'Oregon City', '97045', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1028 Green View Court', 'Chula Vista', '91910', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1028 Green View Court', 'Oregon City', '97045', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1037 Hayes Court', 'Stoke-on-Trent', 'AS23', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1039 Adelaide St.', 'West Covina', '91791', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('104 Hilltop Dr.', 'Springwood', '2777', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('104 Kaski Ln.', 'Portland', '97205', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1040 Greenbush Drive', 'Silverwater', '2264', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1040 Northridge Road', 'London', 'W1X3SE', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1044 San Carlos', 'Cincinnati', '45202', 'Ohio');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1045 Lolita Drive', 'Torrance', '90505', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1045 Lolita Drive', 'Townsville', '4810', 'Queensland');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1047 Las Quebradas Lane', 'North Sydney', '2055', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1048 Burwood Way', 'Hervey Bay', '4655', 'Queensland');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1048 Las Quebradas Lane', 'Walla Walla', '99362', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1048 Las Quebradas Lane', 'Wollongong', '2500', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('105 Clark Creek Lane', 'Port Macquarie', '2444', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('105 Woodruff Ln.', 'Bellingham', '98225', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1050 Creed Ave', 'London', 'W10 6BL', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('081, boulevard du Montparnasse', 'Seattle', '98104', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1 Smiling Tree Court', 'Los Angeles', '90012', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('100, rue des Rosiers', 'Everett', '98201', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1002 N. Spoonwood Court', 'Berkeley', '94704', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Fremont Street', 'Colma', '94014', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Valley Oak Plaza', 'Langley', 'V3A 4R2', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1005 Valley Oak Plaza', 'London', 'SW6 SBY', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1007 Cardinet Dr.', 'El Cajon', '92020', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1008 Lydia Lane', 'Burbank', '91502', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('101 Candy Rd.', 'Redmond', '98052', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1011 Green St.', 'Bellingham', '98225', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1013 Buchanan Rd', 'Port Macquarie', '2444', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1013 Buchanan Rd', 'Yakima', '98901', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1016 Park Avenue', 'Burbank', '91502', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Book Road', 'Rhodes', '2138', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Buchanan Road', 'Woodland Hills', '91364', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Candy Rd.', 'Coffs Harbour', '2450', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Chance Drive', 'Sedro Woolley', '98284', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Kenwal Rd.', 'Lake Oswego', '97034', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1019 Pennsylvania Blvd', 'Marysville', '98270', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('102 Vista Place', 'Milton Keynes', 'MK8 8DF', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('10203 Acorn Avenue', 'Calgary', 'T2P 2G8', 'Alberta');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1023 Hawkins Street', 'Townsville', '4810', 'Queensland');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1023 Riveria Way', 'Burbank', '91502', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1023 Riviera Way', 'Oxford', 'OX1', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1025 Yosemite Dr.', 'Townsville', '4810', 'Queensland');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1026 Mt. Wilson Pl.', 'Lynnwood', '98036', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1026 Mt. Wilson Pl.', 'South Melbourne', '3205', 'Victoria');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1028 Indigo Ct.', 'Issaquah', '98027', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1028 Indigo Ct.', 'Warrnambool', '3280', 'Victoria');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1028 Royal Oak Rd.', 'Burlingame', '94010', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1029 Birchwood Dr', 'Burien', '98168', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1029 Birchwood Dr', 'Olympia', '98501', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1030 Ambush Dr.', 'Bury', 'PE17', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1032 Buena Vista', 'North Ryde', '2113', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1032 Coats Road', 'Stoke-on-Trent', 'AS23', 'England');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1035 Arguello Blvd.', 'San Diego', '92102', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1036 Mason Dr', 'Port Orchard', '98366', 'Washington');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1039 Adelaide St.', 'Port Macquarie', '2444', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('104 Hilltop Dr.', 'Concord', '94519', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1040 Greenbush Drive', 'Newton', 'V2L3W8', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1040 Northridge Road', 'Woodland Hills', '91364', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1042 Hooftrail Way', 'Newcastle', '2300', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1046 Cloverleaf Circle', 'Shawnee', 'V8Z 4N5', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1046 San Carlos Avenue', 'Colma', '94014', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1047 Las Quebradas Lane', 'Oak Bay', 'V8P', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1048 Burwood Way', 'Haney', 'V2W 1W2', 'British Columbia');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('105 Woodruff Ln.', 'Oakland', '94611', 'California');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1050 Creed Ave', 'Lebanon', '97355', 'Oregon');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1050 Greenhills Circle', 'Lane Cove', '1597', 'New South Wales');
INSERT INTO s17guest50.dbo.Address (street, city, zipPostal, stateProvinceCountry) VALUES ('1050 Greenhills Circle', 'Langley', 'V3A 4R2', 'British Columbia');